### ISSUE TITLE
Procon.Net.Protocols.Frostbite can be merged with Procon.Net

### ISSUE THREAD

**Issue by phogue** [phogue/Potato#5]
Since the protocol is maintained by us this project can be merged back into Procon.Net. We still require the functionality for loading external protocol dll's so others can implement their own support for protocols, but it feels messy splitting up Myrcon provided protocols into their own dll's.

We should then create a test Procon.Net.Protocols.ThirdParty, if anything just to show others they can include their own protocol support and how it can be done.

Procon.Net.Protocols.ThirdParty should exist in its own repository.

**Comment by m4cx** [comment]
I would say, that each protocol has or can have it's own special behaviour. Just look at the differences in BF3 and BF4. In my opinion every change on the codebase touches the whole system. Seperation in DLL is one of the ways to keep dependencies low.

Loose Coupling is the keyword.
http://en.wikipedia.org/wiki/Loose_coupling
