### ISSUE TITLE
Include AbbreviatedName in game mode 

### ISSUE THREAD

**Issue by phogue** [phogue/Potato#67]
The configs for BF3/BF4 require an additional field in each game mode (just the top definitions)

```
{
            "Name": "SquadDeathMatch0",
            "FriendlyName": "Squad Deathmatch",
            "TeamCount": "4",
            "DefaultGroups": [
                {
                    "Uid": "0",
                    "Type": "Squad"
                }
            ]
        }
```

Using the following the abbreviated name would be "SQDM", conquest "CQST" - whatever keeps it short and understandable to people that have played the game long enough to rent a server.

It's not limited to 4 chars. Just as short as possible while still making sense.

```
{
            "Name": "SquadDeathMatch0",
            "FriendlyName": "Squad Deathmatch",
            "AbbreviatedName": "SQDM",
            "TeamCount": "4",
            "DefaultGroups": [
                {
                    "Uid": "0",
                    "Type": "Squad"
                }
            ]
        }
```

The resulting config should be run through http://jsonformatter.curiousconcept.com/ or another json validator to ensure the merge is a success :)

@EBassie can you have a look at this?

**Comment by EBassie** [comment]
Done

**Comment by phogue** [comment]
#69 and #68 close this issue
