### ISSUE TITLE
Change Test Framework

### ISSUE THREAD

**Issue by m4cx** [phogue/Potato#7]
The current build server on http://teamcity.codebetter.com does not support MSTest. There is no build agent having the assemblies installed.

NUnit-Runner is installed and can be used.

**Comment by phogue** [comment]
Remove http://teamcity.codebetter.com. I'd prefer not to get emails from it anyway. I can tell when the project I'm working on isn't working, when it's not working.

**Comment by m4cx** [comment]
What do you mean? You don't want to use a build server? Or do you have another build server instance I don't know?

**Comment by MorpheusXAUT** [comment]
We currently don't use build servers, but mainly just build the project independently when needed.
Releases are also compiled manually before being distributed.

**Comment by m4cx** [comment]
Ok, but we should think about using them. This can avoid "works on my machine" problems. So I think we should swith to another unit-testing framework, that is not that tightly coupled with Visual Studio like MSTest is. I also thought about xUnit.NET.

**Comment by phogue** [comment]
Closing after merge. See #9
